import { describe, expect, it } from "vitest";
import { Range, TextEdit } from "vscode-languageserver";

import { RegistryIndex } from "../index";
import { extractMarkdown, looksLikeWeaverDoc } from "../markdown";
import { extract } from "../model";
import { OffsetConverter } from "../parser";
import { buildRenameEdits } from "../rename";

const URI = "file:///docs/gen-ai.md";

function tokenText(text: string, range: { start: any; end: any }): string {
  const lines = text.split("\n");
  return lines[range.start.line].slice(range.start.character, range.end.character);
}

describe("looksLikeWeaverDoc", () => {
  it("detects a weaver directive, ignores plain markdown and endweaver", () => {
    expect(looksLikeWeaverDoc("<!-- weaver .registry.events[] -->")).toBe(true);
    expect(looksLikeWeaverDoc("# Heading\n\nsome prose with the word weaver")).toBe(false);
    expect(looksLikeWeaverDoc("<!-- endweaver -->")).toBe(false);
  });
});

describe("extractMarkdown", () => {
  it("captures signal ids by their selector field with precise ranges", () => {
    const md = [
      `<!-- weaver .registry.events[] | select(.name == "gen_ai.evaluation.result") -->`,
      `<!-- weaver .registry.metrics[] | select(.name == "gen_ai.client.token.usage") -->`,
      `<!-- weaver .registry.spans[] | select(.type == "gen_ai.inference.client") -->`,
      `<!-- weaver .registry.entities[] | select(.type == "gen_ai.agent") -->`,
    ].join("\n");
    const refs = extractMarkdown(md, URI);

    const byKind = (k: string) => refs.filter((r) => r.refKind === k).map((r) => r.id);
    expect(byKind("md_event_ref")).toEqual(["gen_ai.evaluation.result"]);
    expect(byKind("md_metric_ref")).toEqual(["gen_ai.client.token.usage"]);
    expect(byKind("md_span_ref")).toEqual(["gen_ai.inference.client"]);
    expect(byKind("md_entity_ref")).toEqual(["gen_ai.agent"]);

    const event = refs.find((r) => r.refKind === "md_event_ref")!;
    expect(tokenText(md, event.range)).toBe("gen_ai.evaluation.result");
  });

  it("resolves refinement ids and nested attribute-key filters", () => {
    const md =
      `<!-- weaver .refinements.spans[] | select(.id == "openai.inference.client")` +
      ` | .attributes |= map(select(.key != "gen_ai.provider.name")) -->`;
    const refs = extractMarkdown(md, URI);

    const refinement = refs.find((r) => r.refKind === "md_span_refinement_ref")!;
    expect(refinement.id).toBe("openai.inference.client");

    const attr = refs.find((r) => r.refKind === "md_attribute_ref")!;
    expect(attr.id).toBe("gen_ai.provider.name");
    expect(tokenText(md, attr.range)).toBe("gen_ai.provider.name");
  });

  it("honours the template: prefix and ignores it as a reference", () => {
    const md = `<!-- weaver template:attributes_only.md.j2 .registry.spans[] | select(.type == "gen_ai.inference.client") -->`;
    const refs = extractMarkdown(md, URI);
    expect(refs).toHaveLength(1);
    expect(refs[0]).toMatchObject({ refKind: "md_span_ref", id: "gen_ai.inference.client" });
  });

  it("ignores autogenerated snippet bodies and non-weaver comments", () => {
    const md = [
      `## Heading`,
      `<!-- weaver .registry.events[] | select(.name == "gen_ai.evaluation.result") -->`,
      `<!-- NOTE: THIS TEXT IS AUTOGENERATED. DO NOT EDIT BY HAND. -->`,
      `The event name MUST be \`gen_ai.evaluation.result\`.`,
      `| [\`gen_ai.evaluation.name\`](registry/attributes/gen-ai.md) | ... |`,
      `<!-- endweaver -->`,
    ].join("\n");
    const refs = extractMarkdown(md, URI);
    expect(refs).toHaveLength(1);
    expect(refs[0].id).toBe("gen_ai.evaluation.result");
  });

  it("returns nothing for markdown without weaver directives", () => {
    expect(extractMarkdown("# Just docs\n\nNo snippets here.", URI)).toEqual([]);
  });
});

const REGISTRY = `file_format: definition/2
events:
  - name: gen_ai.evaluation.result
    stability: development
    brief: Evaluation result.
`;
const REG_URI = "file:///registry.yaml";
const DOC = `## Evaluation result

<!-- weaver .registry.events[] | select(.name == "gen_ai.evaluation.result") -->
<!-- endweaver -->

<!-- weaver .registry.events[] | select(.name == "gen_ai.missing") -->
<!-- endweaver -->
`;

function applyEdits(text: string, edits: TextEdit[]): string {
  const off = new OffsetConverter(text);
  const span = (r: Range): [number, number] => [off.offset(r.start), off.offset(r.end)];
  const sorted = [...edits].sort((a, b) => span(b.range)[0] - span(a.range)[0]);
  let out = text;
  for (const edit of sorted) {
    const [start, end] = span(edit.range);
    out = out.slice(0, start) + edit.newText + out.slice(end);
  }
  return out;
}

describe("markdown – index integration", () => {
  function setup(): RegistryIndex {
    const index = new RegistryIndex();
    const yaml = extract(REGISTRY, REG_URI);
    index.setDocument(REG_URI, yaml.defs, yaml.refs, yaml.hasImports);
    index.setDocument(URI, [], extractMarkdown(DOC, URI), false);
    return index;
  }

  it("treats a weaver ref as a reference to the yaml definition", () => {
    const index = setup();
    const refs = index.referencesFor("gen_ai.evaluation.result", "event");
    expect(refs.map((r) => r.uri)).toContain(URI);
  });

  it("flags weaver refs with no matching definition as unresolved", () => {
    const index = setup();
    const unresolved = index.unresolvedReferences(URI).map((r) => r.id);
    expect(unresolved).toEqual(["gen_ai.missing"]);
  });

  it("renames the weaver snippet query when the event is renamed", async () => {
    const index = setup();
    const def = index.definitionsFor("gen_ai.evaluation.result", ["event"])[0];
    const texts = new Map([
      [REG_URI, REGISTRY],
      [URI, DOC],
    ]);
    const edit = await buildRenameEdits(
      index,
      REG_URI,
      def.nameRange.start,
      "gen_ai.eval.result",
      (u) => Promise.resolve(texts.get(u)),
    );
    const doc = applyEdits(DOC, edit!.changes![URI]);
    expect(doc).toContain(`select(.name == "gen_ai.eval.result")`);
    expect(doc).toContain(`select(.name == "gen_ai.missing")`);
  });
});
