import { OffsetConverter } from "./parser";
import { Reference, RefKind } from "./types";

// Weaver renders markdown snippets between `<!-- weaver <query> -->` and
// `<!-- endweaver -->`. Only the query in the opening directive is hand-authored
// (the body below it is autogenerated and rewritten in place), so it is the only
// part we index, navigate, and rename — the body is left to weaver to regenerate.

interface Collection {
  idField: string;
  refKind: RefKind;
}

// `.registry.<plural>` selects definitions by their id field; `.refinements.<plural>`
// selects refinements by their own `id`.
const COLLECTIONS: Record<string, Record<string, Collection>> = {
  registry: {
    attributes: { idField: "key", refKind: "md_attribute_ref" },
    events: { idField: "name", refKind: "md_event_ref" },
    metrics: { idField: "name", refKind: "md_metric_ref" },
    spans: { idField: "type", refKind: "md_span_ref" },
    entities: { idField: "type", refKind: "md_entity_ref" },
  },
  refinements: {
    events: { idField: "id", refKind: "md_event_refinement_ref" },
    metrics: { idField: "id", refKind: "md_metric_refinement_ref" },
    spans: { idField: "id", refKind: "md_span_refinement_ref" },
    entities: { idField: "id", refKind: "md_entity_refinement_ref" },
  },
};

const DIRECTIVE = /(<!--\s*weaver\b)([\s\S]*?)(-->)/g;
const COLLECTION = /\.(registry|refinements)\.([a-z_]+)/;
// A jq equality/inequality filter on a field against a quoted id, e.g. `.name == "x"`.
const FILTER = /\.([a-z_][\w]*)\s*[!=]=\s*"([^"]*)"/g;

/** Whether `text` carries at least one weaver snippet directive worth indexing. */
export function looksLikeWeaverDoc(text: string): boolean {
  return /<!--\s*weaver\b/.test(text);
}

/** References to semconv ids found in `<!-- weaver ... -->` snippet queries. */
export function extractMarkdown(text: string, uri: string): Reference[] {
  const refs: Reference[] = [];
  if (!text.includes("weaver")) return refs;
  const off = new OffsetConverter(text);

  DIRECTIVE.lastIndex = 0;
  for (let m = DIRECTIVE.exec(text); m; m = DIRECTIVE.exec(text)) {
    const body = m[2];
    const bodyStart = m.index + m[1].length;

    const collMatch = COLLECTION.exec(body);
    const collection = collMatch ? COLLECTIONS[collMatch[1]]?.[collMatch[2]] : undefined;

    FILTER.lastIndex = 0;
    for (let f = FILTER.exec(body); f; f = FILTER.exec(body)) {
      const field = f[1];
      const value = f[2];
      const refKind = refKindFor(field, collection);
      if (!refKind) continue;

      const valueStart = bodyStart + f.index + f[0].indexOf('"') + 1;
      refs.push({
        refKind,
        id: value,
        uri,
        range: off.range(valueStart, valueStart + value.length),
      });
    }
  }
  return refs;
}

function refKindFor(field: string, collection: Collection | undefined): RefKind | undefined {
  // `.key` is always an attribute, even in a nested filter that drops one from a table.
  if (field === "key") return "md_attribute_ref";
  if (collection && field === collection.idField) return collection.refKind;
  return undefined;
}
